import { Section } from '../types';

export const sectionsListArr: Section[] = [
  { id: '1', title: 'Introduction' },
  { id: '2', title: 'Installation' },
  { id: '3', title: 'Usage' },
  { id: '4', title: 'Contributing' },
  { id: '5', title: 'License' },
  { id: '6', title: 'Badges 🏅' },
  { id: '7', title: 'Demo 🎥' },
  { id: '8', title: 'Deployment 🚀' },
  { id: '9', title: 'Documentation 📚' },
  { id: '10', title: 'Environment Variables 🌱' },
  { id: '11', title: 'FAQ ❓' },
  { id: '12', title: 'Features ✨' },
  { id: '13', title: 'Technologies Used 🛠️' },
  { id: '14', title: 'Screenshots 📸' },
  { id: '15', title: 'Run Locally 🖥️' },
  { id: '16', title: 'Acknowledgements 🙏' },
  { id: '17', title: 'Changelog 📝' },
  { id: '18', title: 'Support 🙋‍♂️' },
  { id: '19', title: 'Contact 📬' },
  { id: '20', title: 'GitHub Profile - About Me 👤' },
  { id: '21', title: 'GitHub Profile - Stats 📊' },
  { id: '22', title: 'GitHub Profile - My Repos 📁' },
  { id: '23', title: 'GitHub Profile - GitHub Contributions 🌱' },
  { id: '24', title: 'GitHub Profile - Current Projects 🚀' },
  { id: '25', title: 'To Do 📝' },
];